AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-world-ts

  Sample SAM Template for hello-world-ts

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/app
      Handler: app.default
      Runtime: nodejs8.10
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0/1 * * * ? *)

Outputs:
  HelloWorldFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt SchedulerFunction.Arn
  HelloWorldFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt SchedulerFunctionRole.Arn
